### ISSUE TITLE
10.1 patch error

### ISSUE THREAD

**Issue by Rezy942** [wyldclaw/betterworldmap-dragonflight#3]
Hello, not sure how I got the error, but here in case it helps:

2x ...aceBetterWorldMap_Dragonflight/core/core.lua:142: Usage: EJ_GetTierInfo(index) Invalid index 10
[string "=[C]"]: in function `EJ_GetTierInfo'
[string "@BetterWorldMap_Dragonflight/core/core.lua"]:142: in function <...aceBetterWorldMap_Dragonflight/core/core.lua:133>
[string "=[C]"]: ?
[string "@BetterWardrobe/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ns/BetterWardrobe/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BetterWardrobe/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@BetterWardrobe/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ns/BetterWardrobe/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
(*temporary) = 10

Also on unrelated note - can we get zaralek cavern points on world map? :)
![image](https://user-images.githubusercontent.com/122007087/235833267-b5b9ded4-b9b4-4a1a-bec1-3242935fe579.png)

Thanks!!!

**Comment by Rezy942** [comment]
Update: error happens on every login - after that, unsure what causes it to popup again.

**Comment by wyldclaw** [comment]
This error will be fixed in the next update. I also aded Zaralek Cavern entrances too! (Pretty late but at least it happened)

**Comment by Rezy942** [comment]
Yea i ended up just deleting the addon all together. It is fantastic but waiting nearly 3 months for it to work every patch will be a bummer. I understand addons need maintenance work, I get it, it sucks that blizz keeps changing everything constantly.
But I also get tired of figuring out what broke every patch and posting bug threads that dont get looked at for months.
Cheers
